// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOHLWeEIfg9z1uACbdN4m4tZwFsi3U0o',
    appId: '1:442566553943:web:3f24059bbf8dc8b330ce12',
    messagingSenderId: '442566553943',
    projectId: 'oasis-app-6eb21',
    authDomain: 'oasis-app-6eb21.firebaseapp.com',
    storageBucket: 'oasis-app-6eb21.firebasestorage.app',
    measurementId: 'G-JW65M4V8T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWOgH6VFW1rq0ZjsM-ZhSYGDXAZ8ASaw',
    appId: '1:442566553943:android:d8bcda92e8960c5230ce12',
    messagingSenderId: '442566553943',
    projectId: 'oasis-app-6eb21',
    storageBucket: 'oasis-app-6eb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1oK8DekLtNmwHW_S6pzcOfFYgeiHIb0Q',
    appId: '1:442566553943:ios:fe429a99e1d42f1c30ce12',
    messagingSenderId: '442566553943',
    projectId: 'oasis-app-6eb21',
    storageBucket: 'oasis-app-6eb21.firebasestorage.app',
    iosBundleId: 'com.example.oasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1oK8DekLtNmwHW_S6pzcOfFYgeiHIb0Q',
    appId: '1:442566553943:ios:fe429a99e1d42f1c30ce12',
    messagingSenderId: '442566553943',
    projectId: 'oasis-app-6eb21',
    storageBucket: 'oasis-app-6eb21.firebasestorage.app',
    iosBundleId: 'com.example.oasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOHLWeEIfg9z1uACbdN4m4tZwFsi3U0o',
    appId: '1:442566553943:web:ae6cd0ead30a9ab730ce12',
    messagingSenderId: '442566553943',
    projectId: 'oasis-app-6eb21',
    authDomain: 'oasis-app-6eb21.firebaseapp.com',
    storageBucket: 'oasis-app-6eb21.firebasestorage.app',
    measurementId: 'G-86V599HJTG',
  );

}